class PopulateNeighborhoods < ActiveRecord::Migration
  def self.up
    Neighborhood.create!(:city_id =>1, :name => 'Lenox', :grouping => 'Buckhead')
    Neighborhood.create!(:city_id =>1, :name => 'South Buckhead', :grouping => 'Buckhead')
    Neighborhood.create!(:city_id =>1, :name => 'West Paces Corridor', :grouping => 'Buckhead')
    Neighborhood.create!(:city_id =>1, :name => 'Buckhead Village', :grouping => 'Buckhead')
    Neighborhood.create!(:city_id =>1, :name => 'Lindbergh', :grouping => 'Buckhead')
    Neighborhood.create!(:city_id =>1, :name => 'Castleberry Hill', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'Centennial Hill', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'Fairlie Poplar', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'Marietta Street', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'SoNo', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'Sweet Auburn', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'Five Points / MLK Drive', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>1, :name => 'Cultural Corridor', :grouping => 'Midtown')
    Neighborhood.create!(:city_id =>1, :name => 'Atlantic Station', :grouping => 'Midtown')
    Neighborhood.create!(:city_id =>1, :name => 'Piedmont Park', :grouping => 'Midtown')
    Neighborhood.create!(:city_id =>1, :name => 'Decatur', :grouping => 'Atlanta East')
    Neighborhood.create!(:city_id =>1, :name => 'Emory / Druid Hills', :grouping => 'Atlanta East')
    Neighborhood.create!(:city_id =>1, :name => 'Stone Mountain', :grouping => 'Atlanta East')
    Neighborhood.create!(:city_id =>1, :name => 'College Park / East Point', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Smyrna', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Cobb Galleria Area', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Douglasville', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Sandy Springs', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Dunwoody', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Vinings', :grouping => 'Atlanta Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Little Five Points', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Grant Park', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Cabbagetown', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Inman Park', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Poncey Highland', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Virginia Highland', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Old Fouth Ward', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'West End', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Cascade Heights', :grouping => 'Intown ')
    Neighborhood.create!(:city_id =>1, :name => 'Kennesaw', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Marietta', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Alpharetta', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Roswell', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Gwinnet County', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Henry Country', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>1, :name => 'Clayton County', :grouping => 'Outside the Perimeter')
    Neighborhood.create!(:city_id =>2, :name => 'Cambridgeport', :grouping => 'Cambridge')
    Neighborhood.create!(:city_id =>2, :name => 'Central Sq / Inman Sq', :grouping => 'Cambridge')
    Neighborhood.create!(:city_id =>2, :name => 'East Cambridge', :grouping => 'Cambridge')
    Neighborhood.create!(:city_id =>2, :name => 'Harvard Square', :grouping => 'Cambridge')
    Neighborhood.create!(:city_id =>2, :name => 'Porter Sq / Fresh Pond', :grouping => 'Cambridge')
    Neighborhood.create!(:city_id =>2, :name => 'Allston', :grouping => 'Allston/Brighton')
    Neighborhood.create!(:city_id =>2, :name => 'Brighton', :grouping => 'Allston/Brighton')
    Neighborhood.create!(:city_id =>2, :name => 'Brookline', :grouping => 'Allston/Brighton')
    Neighborhood.create!(:city_id =>2, :name => 'Chestnut Hill', :grouping => 'Allston/Brighton')
    Neighborhood.create!(:city_id =>2, :name => 'Fenway / Kenmore', :grouping => 'Fenway / Kenmore')
    Neighborhood.create!(:city_id =>2, :name => 'Jamaica Plain', :grouping => 'Fenway / Kenmore')
    Neighborhood.create!(:city_id =>2, :name => 'Symphony/ Northeastern', :grouping => 'Fenway / Kenmore')
    Neighborhood.create!(:city_id =>2, :name => 'Back Bay', :grouping => 'Back Bay')
    Neighborhood.create!(:city_id =>2, :name => 'Beacon Hill', :grouping => 'Back Bay')
    Neighborhood.create!(:city_id =>2, :name => 'South End', :grouping => 'Back Bay')
    Neighborhood.create!(:city_id =>2, :name => 'Charlestown', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'East Boston', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'Faneuil Hall-Govt Center', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'Financial District', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'Garden / MGH', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'Harbor', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'North End', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>2, :name => 'Theatre Dist / Chinatown', :grouping => 'Downtown/North End')
    Neighborhood.create!(:city_id =>3, :name => 'Albany Park / North Park', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Far NW Chicago', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Hermosa', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Humboldt-Austin-Garfield', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Irving Park', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Logan Square / Avondale)', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Montclare / Cragin', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Old Town / Goose Island', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Portage Park / Dunning', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Rogers Park / Devon Ave', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Roscoe Village / North Ctr', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Ukranian Village', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Wicker Park / Bucktown', :grouping => 'Northwest Side')
    Neighborhood.create!(:city_id =>3, :name => 'Albany Park / North Park', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Edgewater / Andersonville', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Far NW Chicago', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Hermosa', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Irving Park', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Lincoln Park / DePaul', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Lincoln Sq / Ravenswood', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Logan Square / Avondale', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Old Town / Goose Island', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Rogers Park / Devon Ave', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Roscoe Village / North Ctr', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Uptown', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Wicker Park / Bucktown', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Wrigleyville / Lakeview', :grouping => 'North Side')
    Neighborhood.create!(:city_id =>3, :name => 'Albany Park / North Park', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Archer Hts / Brighton Pk', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Hermosa', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Humboldt-Austin-Garfield', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Lawndale', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Montclare / Cragin', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Near West', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Ukranian Village', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'West Loop / Greektown', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Wicker Park / Bucktown', :grouping => 'West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Chinatown / Pilsen', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Gold Coast', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Hermosa', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Humboldt-Austin-Garfield', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Irving Park', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Lawndale', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Lincoln Park / DePaul', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Lincoln Sq / Ravenswood', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Logan Square / Avondale', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Loop', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Near West', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Old Town / Goose Island', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'River North', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'South Loop / Near South', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Streeterville', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Ukranian Village', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'West Loop / Greektown', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Wicker Park / Bucktown', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>3, :name => 'Archer Hts / Brighton Pk', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Chicago Lawn / Ashburn', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Chinatown / Pilsen', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Far SW Chicago', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Lawndale', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Midway', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'New City / Chatham', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'South Side', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Bridgeport-McKinley Park', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Bronzeville / Douglas', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Chinatown / Pilsen', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Edgewater / Andersonville', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Far SE Chicago', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Far SW Chicago', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Hyde Park / Kenwood', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'Midway', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'New City / Chatham', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>3, :name => 'South Shore / Woodlawn', :grouping => 'South West Side')
    Neighborhood.create!(:city_id =>8, :name => 'Burbank', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'Encino', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'North Hollywood', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'Sherman Oaks', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'Studio City', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'Universal City', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'Westchester', :grouping => 'The Valley')
    Neighborhood.create!(:city_id =>8, :name => 'Hancock Park', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'Hermosa Beach', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'Hollywood', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'Los Feliz', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'North Hollywood', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'Silver Lake / Echo Park', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'Universal City', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'West Hollywood', :grouping => 'Hollywood')
    Neighborhood.create!(:city_id =>8, :name => 'Baldwin Hills / Jefferson Park', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Beverly Hills', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Brentwood', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Century City', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Culver City', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Fairfax', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Hollywood', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Marina del Rey', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Santa Monica', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'West Hollywood', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'West LA', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Westchester', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Westwood', :grouping => 'The Westside: City')
    Neighborhood.create!(:city_id =>8, :name => 'Beverly Hills', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'El Segundo', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Hermosa Beach', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Malibu', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Manhattan Beach', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Marina del Rey', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Pacific Palisades', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Redondo Beach', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Santa Monica', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Venice', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'West LA', :grouping => 'The Westside: Coastal')
    Neighborhood.create!(:city_id =>8, :name => 'Baldwin Hills / Jefferson Park', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Beverly Hills', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Culver City', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Fairfax', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Hancock Park', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Inglewood', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Koreatown', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Mid-City', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Studio City', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'West Hollywood', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'West LA', :grouping => 'Mid-Wilshire')
    Neighborhood.create!(:city_id =>8, :name => 'Chinatown', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>8, :name => 'Downtown', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>8, :name => 'Little Tokyo', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>8, :name => 'Silver Lake / Echo Park', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>8, :name => 'Westlake / Pico U', :grouping => 'Downtown')
    Neighborhood.create!(:city_id =>8, :name => 'Eagle Rock', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Highland Park / El Sereno', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Los Feliz', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Montebello/ City of Commerce', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Monterey Park / East LA', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Silver Lake / Echo Park', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Westlake / Pico Union', :grouping => 'The East Side')
    Neighborhood.create!(:city_id =>8, :name => 'Carson', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Catalina Island', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'El Segundo', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Gardena', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Hawthorne / Lawndale', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Lomita', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Rancho Palos Verdes', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Redondo Beach', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'San Pedro', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Santa Monica', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'Torrance', :grouping => 'South Bay: City')
    Neighborhood.create!(:city_id =>8, :name => 'El Segundo', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>8, :name => 'Hermosa Beach', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>8, :name => 'Manhattan Beach', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>8, :name => 'Rancho Palos Verdes', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>8, :name => 'Redondo Beach', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>8, :name => 'San Pedro', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>8, :name => 'Venice', :grouping => 'South Bay: Beach Cities')
    Neighborhood.create!(:city_id =>10, :name => 'Aventura / Sunny Isles', :grouping => 'Northeast Dade')
    Neighborhood.create!(:city_id =>10, :name => 'North Miami Beach', :grouping => 'Northeast Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Miami Gardens / Opa-Locka', :grouping => 'Northeast Dade')
    Neighborhood.create!(:city_id =>10, :name => 'North Miami', :grouping => 'Northeast Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Pinewood Park / Miami Shores', :grouping => 'Northeast Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Little Havana / Flagami', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'South Miami / Pinecrest', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Miami Lakes / Palm Springs North', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Miami Gardens / Opa-Locka', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Pinewood Park / Miami Shores', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Hialeah', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Allapattah / Overtown / Liberty City', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Miami Springs / Airport', :grouping => 'Northwest Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Downtown / Brickell', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'Wynwood / Design District', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'South Beach', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'North Beach', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'Coconut Grove', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'Key Biscayne', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'Shenandoah', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'Westwood Lakes', :grouping => 'Miami / Miami Beach')
    Neighborhood.create!(:city_id =>10, :name => 'Little Havana / Flagami', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Coral Gables', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'South Miami / Pinecrest', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'West Miami / Westchester', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Kendall', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Sweetwater / Doral', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Westwood Lakes', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Cutler Bay / Perrine / Redland', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>10, :name => 'Homestead / Florida City', :grouping => 'South Dade')
    Neighborhood.create!(:city_id =>9, :name => "East 90's", :grouping => 'Uptown')
    Neighborhood.create!(:city_id =>9, :name => 'Harlem', :grouping => 'Uptown')
    Neighborhood.create!(:city_id =>9, :name => 'East Harlem', :grouping => 'Uptown')
    Neighborhood.create!(:city_id =>9, :name => 'Morningside Heights', :grouping => 'Uptown')
    Neighborhood.create!(:city_id =>9, :name => 'Washington Hts / Inwood', :grouping => 'Uptown')
    Neighborhood.create!(:city_id =>9, :name => "West 60's", :grouping => 'UWS')
    Neighborhood.create!(:city_id =>9, :name => "West 70's", :grouping => 'UWS')
    Neighborhood.create!(:city_id =>9, :name => "West 80's", :grouping => 'UWS')
    Neighborhood.create!(:city_id =>9, :name => "West 90's & 100's", :grouping => 'UWS')
    Neighborhood.create!(:city_id =>9, :name => 'Morningside Heights', :grouping => 'UWS')
    Neighborhood.create!(:city_id =>9, :name => "East 50's", :grouping => 'Midtown West / Theatre District')
    Neighborhood.create!(:city_id =>9, :name => "West 40's", :grouping => 'Midtown West / Theatre District')
    Neighborhood.create!(:city_id =>9, :name => "West 50's", :grouping => 'Midtown West / Theatre District')
    Neighborhood.create!(:city_id =>9, :name => "West 60's", :grouping => 'Midtown West / Theatre District')
    Neighborhood.create!(:city_id =>9, :name => "West 30's", :grouping => 'Chelsea / Midtown South')
    Neighborhood.create!(:city_id =>9, :name => "West 40's", :grouping => 'Chelsea / Midtown South')
    Neighborhood.create!(:city_id =>9, :name => 'Flatiron / Union Square', :grouping => 'Chelsea / Midtown South')
    Neighborhood.create!(:city_id =>9, :name => 'Chelsea / Midtown South', :grouping => 'Chelsea / Midtown South')
    Neighborhood.create!(:city_id =>9, :name => 'Central Village / Noho', :grouping => ' Village/ W Village')
    Neighborhood.create!(:city_id =>9, :name => 'West Village', :grouping => ' Village/ W Village')
    Neighborhood.create!(:city_id =>9, :name => 'Soho / Little Italy', :grouping => 'Soho/Trbca/FinDist')
    Neighborhood.create!(:city_id =>9, :name => 'Tribeca', :grouping => 'Soho/Trbca/FinDist')
    Neighborhood.create!(:city_id =>9, :name => 'Chinatown / Two Bridges', :grouping => 'Soho/Trbca/FinDist')
    Neighborhood.create!(:city_id =>9, :name => 'Financial District', :grouping => 'Soho/Trbca/FinDist')
    Neighborhood.create!(:city_id =>9, :name => "East 60's", :grouping => 'UES')
    Neighborhood.create!(:city_id =>9, :name => "East 70's", :grouping => 'UES')
    Neighborhood.create!(:city_id =>9, :name => "East 80's", :grouping => 'UES')
    Neighborhood.create!(:city_id =>9, :name => "East 90's", :grouping => 'UES')
    Neighborhood.create!(:city_id =>9, :name => "East 40's", :grouping => 'Midtown East')
    Neighborhood.create!(:city_id =>9, :name => "East 50's", :grouping => 'Midtown East')
    Neighborhood.create!(:city_id =>9, :name => "East 60's", :grouping => 'Midtown East')
    Neighborhood.create!(:city_id =>9, :name => "East 90's", :grouping => 'Midtown East')
    Neighborhood.create!(:city_id =>9, :name => "West 30's", :grouping => 'Midtown East')
    Neighborhood.create!(:city_id =>9, :name => "West 50's", :grouping => 'Midtown East')
    Neighborhood.create!(:city_id =>9, :name => "East 30's", :grouping => 'Murray Hill / Gramercy')
    Neighborhood.create!(:city_id =>9, :name => "East 40's", :grouping => 'Murray Hill / Gramercy')
    Neighborhood.create!(:city_id =>9, :name => 'Gramercy / Kips Bay', :grouping => 'Murray Hill / Gramercy')
    Neighborhood.create!(:city_id =>9, :name => 'Flatiron / Union Square', :grouping => 'Murray Hill / Gramercy')
    Neighborhood.create!(:city_id =>9, :name => 'East Village', :grouping => 'East Village/ LES')
    Neighborhood.create!(:city_id =>9, :name => 'Lower East Side', :grouping => 'East Village/ LES')
    Neighborhood.create!(:city_id =>11, :name => 'City Avenue', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'Far Northeast', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'Mid Northeast', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'Conshohocken / Ply Mtng', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'King of Prussia', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'Lower Merion / Haverford', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'Willow Grove / Huntg Val', :grouping => 'Montgomery County W')
    Neighborhood.create!(:city_id =>11, :name => 'Chestnut Hill', :grouping => 'Montgomery County E')
    Neighborhood.create!(:city_id =>11, :name => 'Conshohocken / Ply Mtng', :grouping => 'Montgomery County E')
    Neighborhood.create!(:city_id =>11, :name => 'Glenside / North Hills', :grouping => 'Montgomery County E')
    Neighborhood.create!(:city_id =>11, :name => 'Jenkintown / Abington', :grouping => 'Montgomery County E')
    Neighborhood.create!(:city_id =>11, :name => 'Lower Merion / Haverford', :grouping => 'Montgomery County E')
    Neighborhood.create!(:city_id =>11, :name => 'Willow Grove / Huntg Val', :grouping => 'Montgomery County E')
    Neighborhood.create!(:city_id =>11, :name => 'Southwest Philadelphia', :grouping => 'Delaware County')
    Neighborhood.create!(:city_id =>11, :name => 'Lower Merion / Haverford', :grouping => 'Delaware County')
    Neighborhood.create!(:city_id =>11, :name => 'Springfield / Drexel Hill', :grouping => 'Delaware County')
    Neighborhood.create!(:city_id =>11, :name => 'Upper Darby', :grouping => 'Delaware County')
    Neighborhood.create!(:city_id =>11, :name => 'Wayne/Radnor', :grouping => 'Delaware County')
    Neighborhood.create!(:city_id =>11, :name => 'City Avenue', :grouping => 'University City/W Philly')
    Neighborhood.create!(:city_id =>11, :name => 'South Philadelphia', :grouping => 'University City/W Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Southwest Philadelphia', :grouping => 'University City/W Philly')
    Neighborhood.create!(:city_id =>11, :name => 'University City', :grouping => 'University City/W Philly')
    Neighborhood.create!(:city_id =>11, :name => 'West Philadelphia', :grouping => 'University City/W Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Lower Merion / Haverford', :grouping => 'University City/W Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Chestnut Hill', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Fishtown / Port Richmond', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Manayunk', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Mount Airy / Germantown', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'North Philadelphia', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Old City-Northern Librties', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Conshohocken / Ply Mtng', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Lower Merion / Haverford', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Wayne/Radnor', :grouping => 'NW Philly/N Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Art Museum', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Bella Vista / Queens Vil', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Center City East', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Center City West', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Chinatown / Conven Ctr', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'City Avenue', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Fishtown / Port Richmond', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Graduate Hospital', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Old City-Northern Librties', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'South Street', :grouping => 'Center City')
    Neighborhood.create!(:city_id =>11, :name => 'Art Museum', :grouping => 'South Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Bella Vista / Queens Vil', :grouping => 'South Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Graduate Hospital', :grouping => 'South Philly')
    Neighborhood.create!(:city_id =>11, :name => 'South Philadelphia', :grouping => 'South Philly')
    Neighborhood.create!(:city_id =>11, :name => 'South Street', :grouping => 'South Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Center City East', :grouping => 'NE Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Far Northeast', :grouping => 'NE Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Fishtown / Port Richmond', :grouping => 'NE Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Mid Northeast', :grouping => 'NE Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Old City-Northern Librties', :grouping => 'NE Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Bensalem', :grouping => 'NE Philly')
    Neighborhood.create!(:city_id =>11, :name => 'Far Northeast', :grouping => 'Bucks County')
    Neighborhood.create!(:city_id =>11, :name => 'Bensalem', :grouping => 'Bucks County')
    Neighborhood.create!(:city_id =>11, :name => 'Langhorne', :grouping => 'Bucks County')
    Neighborhood.create!(:city_id =>13, :name => 'Inner Richmond', :grouping => 'Richmond')
    Neighborhood.create!(:city_id =>13, :name => 'Outer Richmond', :grouping => 'Richmond')
    Neighborhood.create!(:city_id =>13, :name => 'Chinatown', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Civic Center', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Cow Hollow', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Financial District', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Marina', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Pacific Heights', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Western Addition', :grouping => 'Marina/Heights')
    Neighborhood.create!(:city_id =>13, :name => 'Chinatown', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Civic Center', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Embarcadero', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Financial District', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => "Fisherman's Wharf"  , :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Nob Hill', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'North Beach', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Potrero Hill', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Russian Hill', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'SoMa', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Union Square', :grouping => 'Downtown/Waterfront')
    Neighborhood.create!(:city_id =>13, :name => 'Castro', :grouping => 'SoMa/Mission')
    Neighborhood.create!(:city_id =>13, :name => 'Marina', :grouping => 'SoMa/Mission')
    Neighborhood.create!(:city_id =>13, :name => 'Mission', :grouping => 'SoMa/Mission')
    Neighborhood.create!(:city_id =>13, :name => 'Potrero Hill', :grouping => 'SoMa/Mission')
    Neighborhood.create!(:city_id =>13, :name => 'SoMa', :grouping => 'SoMa/Mission')
    Neighborhood.create!(:city_id =>13, :name => 'Castro', :grouping => 'Haight/Castro/Noe Valley')
    Neighborhood.create!(:city_id =>13, :name => 'Hayes Valley', :grouping => 'Haight/Castro/Noe Valley')
    Neighborhood.create!(:city_id =>13, :name => 'Noe Valley', :grouping => 'Haight/Castro/Noe Valley')
    Neighborhood.create!(:city_id =>13, :name => 'Pacific Heights', :grouping => 'Haight/Castro/Noe Valley')
    Neighborhood.create!(:city_id =>13, :name => 'Western Addition', :grouping => 'Haight/Castro/Noe Valley')
    Neighborhood.create!(:city_id =>13, :name => 'Inner Sunset', :grouping => 'Sunset')
    Neighborhood.create!(:city_id =>13, :name => 'Outer Sunset', :grouping => 'Sunset')
    Neighborhood.create!(:city_id =>15, :name => 'Bethesda / Chevy Chase', :grouping => 'Bethesda / Silver Spring / College Park')
    Neighborhood.create!(:city_id =>15, :name => 'College Park', :grouping => 'Bethesda / Silver Spring / College Park')
    Neighborhood.create!(:city_id =>15, :name => 'Silver Spring', :grouping => 'Bethesda / Silver Spring / College Park')
    Neighborhood.create!(:city_id =>15, :name => 'Downtown', :grouping => 'Upper NW')
    Neighborhood.create!(:city_id =>15, :name => 'Foggy Bottom', :grouping => 'Upper NW')
    Neighborhood.create!(:city_id =>15, :name => 'Georgetown', :grouping => 'Upper NW')
    Neighborhood.create!(:city_id =>15, :name => 'Petworth / Columbia Hts', :grouping => 'Upper NW')
    Neighborhood.create!(:city_id =>15, :name => 'Tenleytown', :grouping => 'Upper NW')
    Neighborhood.create!(:city_id =>15, :name => 'U St / Logan Circle', :grouping => 'Upper NW')
    Neighborhood.create!(:city_id =>15, :name => 'Adams Morgan', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'Downtown', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'Dupont Circle', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'Foggy Bottom', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'Petworth / Columbia Hts', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'U St / Logan Circle', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'Clarendon', :grouping => 'Downtown / Lower NW')
    Neighborhood.create!(:city_id =>15, :name => 'Brookland / Far SE', :grouping => 'Capitol Hill / SW')
    Neighborhood.create!(:city_id =>15, :name => 'Capitol Hill', :grouping => 'Capitol Hill / SW')
    Neighborhood.create!(:city_id =>15, :name => 'Downtown', :grouping => 'Capitol Hill / SW')
    Neighborhood.create!(:city_id =>15, :name => 'Georgetown', :grouping => 'Capitol Hill / SW')
    Neighborhood.create!(:city_id =>15, :name => 'Petworth / Columbia Hts', :grouping => 'Capitol Hill / SW')
    Neighborhood.create!(:city_id =>15, :name => 'SW Waterfront', :grouping => 'Capitol Hill / SW')
    Neighborhood.create!(:city_id =>15, :name => 'Arlington - North', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Ballston', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Clarendon', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Crystal City', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Rosslyn', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Shirlington-Columbia Pke', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Alexandria - South', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Alexandria - West End', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Del Ray', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Old Town', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Annandale', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Falls Church', :grouping => 'Arlington / Alexandria')
    Neighborhood.create!(:city_id =>15, :name => 'Annandale', :grouping => 'Fairfax / Tysons Corner')
    Neighborhood.create!(:city_id =>15, :name => 'Fairfax City', :grouping => 'Fairfax / Tysons Corner')
    Neighborhood.create!(:city_id =>15, :name => 'Falls Church', :grouping => 'Fairfax / Tysons Corner')
    Neighborhood.create!(:city_id =>15, :name => 'McLean', :grouping => 'Fairfax / Tysons Corner')
    Neighborhood.create!(:city_id =>15, :name => 'Tysons Corner', :grouping => 'Fairfax / Tysons Corner')
    Neighborhood.create!(:city_id =>15, :name => 'Vienna', :grouping => 'Fairfax / Tysons Corner')
  end

  def self.down
  end
end
